#!/bin/bash

setup()
{
	echo "make ..."
	make -C ./basic O=../bin
}

do_multi_tests()
{
	bin=./bin
	testcases=$1

	for rule_file in $(ls $testcases)
	do
		total=0
		success=0
		failed=0
		echo ">> $rule_file cases begin"
		while read line
		do
			if [[ "$line" = "^#*" ]]; then
				continue
			fi

			cmd=$bin/$line
			eval $cmd
			if [ $? -eq 0 ]; then
				echo "successful: $line"
				success=$((success+1))
			else
				echo "failed: $line"
				failed=$((failed+1))
			fi
			total=$((total+1))
		done < $testcases/$rule_file
		echo ">> total: $total, success: $success, failed: $failed"
	done
}

do_single_test()
{
	bin=./bin
	rule_file=$1

	total=0
	success=0
	failed=0

	echo ">> $rule_file cases begin"
	while read line
	do
		#echo $line
		if [ "$line" == "" ]; then
			continue
		fi
		if [[ "$line" =~ ^#.* ]]; then
			continue
		fi

		cmd=$bin/$line
		eval $cmd
		if [ $? -eq 0 ]; then
			echo "successful: $line"
			success=$((success+1))
		else
			echo "failed: $line"
			failed=$((failed+1))
		fi
		total=$((total+1))
	done < $rule_file
	echo ">> total: $total, success: $success, failed: $failed"
}

main()
{
	[ ! $# -eq 2 ] && echo "Usage: $0 case-dir case-name" && exit -1

	case_dir=$1
	echo "test begin ..."
	if [ ! -d $case_dir ]; then
		echo "case dir '$case_dir' not exist!"
		exit -1
	fi

	case_name=$2
	case_file=$case_dir/$case_name
	echo "do test for $case_name ..."
	if [ ! -f $case_file ]; then
	       echo "case file '$case_file' not exist!"
	       exit -1
	fi

	do_single_test $case_file
	echo "test end"

}

#setup
main "$@"
