/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XDR_H_RPCGEN
#define _XDR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define USER_NAME_MAX_LEN 33
#define PASSWD_MAX_LEN 17
#define SESSION_ID_LEN 17

struct validate_req {
	int name_len;
	int passwd_len;
	char name[USER_NAME_MAX_LEN];
	char passwd_md5[PASSWD_MAX_LEN];
};
typedef struct validate_req validate_req;
#ifdef __cplusplus
extern "C" bool_t xdr_validate_req(XDR *, validate_req*);
#elif __STDC__
extern  bool_t xdr_validate_req(XDR *, validate_req*);
#else /* Old Style C */
bool_t xdr_validate_req();
#endif /* Old Style C */


struct validate_resp {
	int status;
	u_long uid;
	char name[USER_NAME_MAX_LEN];
	char session_id[SESSION_ID_LEN];
};
typedef struct validate_resp validate_resp;
#ifdef __cplusplus
extern "C" bool_t xdr_validate_resp(XDR *, validate_resp*);
#elif __STDC__
extern  bool_t xdr_validate_resp(XDR *, validate_resp*);
#else /* Old Style C */
bool_t xdr_validate_resp();
#endif /* Old Style C */


#endif /* !_XDR_H_RPCGEN */
