/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REQ_RSP_H_RPCGEN
#define _REQ_RSP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define USER_NAME_MAX_LEN 32
#define PASSWD_MD5_LEN 33
#define SESSION_ID_LEN 32
#define DIR_PATH_MAX_LEN 256

struct validate_req {
	int name_len;
	int passwd_len;
	char name[USER_NAME_MAX_LEN];
	char passwd_md5[PASSWD_MD5_LEN];
};
typedef struct validate_req validate_req;

struct validate_resp {
	int status;
	int uid;
	char name[USER_NAME_MAX_LEN];
	char session_id[SESSION_ID_LEN];
};
typedef struct validate_resp validate_resp;

struct pwd_req {
	char session_id[SESSION_ID_LEN];
};
typedef struct pwd_req pwd_req;

struct pwd_resp {
	int status;
	char pwd[DIR_PATH_MAX_LEN];
};
typedef struct pwd_resp pwd_resp;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_validate_req (XDR *, validate_req*);
extern  bool_t xdr_validate_resp (XDR *, validate_resp*);
extern  bool_t xdr_pwd_req (XDR *, pwd_req*);
extern  bool_t xdr_pwd_resp (XDR *, pwd_resp*);

#else /* K&R C */
extern bool_t xdr_validate_req ();
extern bool_t xdr_validate_resp ();
extern bool_t xdr_pwd_req ();
extern bool_t xdr_pwd_resp ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REQ_RSP_H_RPCGEN */
