#!/bin/bash

server_bin=/root/sftt/server/sfttd
client_bin=/root/sftt/client/sftt


$server_bin stop
nohup $server_bin start > /tmp/nohup.txt 2>&1 &

sleep 1

$client_bin root@127.0.0.1:/root/sftt/test /var/sftt/tmp8/
$client_bin root@127.0.0.1:/root/sftt/README.md /var/sftt/tmp8/
