#!/bin/bash

server_bin=/root/sftt/server/sfttd
client_bin=/root/sftt/client/sftt


$server_bin stop
nohup $server_bin start > /tmp/nohup.txt 2>&1 &

sleep 1

$client_bin /var/sftt/tmp8/ root@127.0.0.1:/var/sftt/tmp9/
$client_bin /var/sftt/tmp8/README.md root@127.0.0.1:/var/sftt/tmp9/
