/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "req_resp.h"

bool_t
xdr_version_info (XDR *xdrs, version_info *objp)
{
	register int32_t *buf;

	 if (!xdr_short (xdrs, &objp->major))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_short (xdrs, &objp->minor))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_short (xdrs, &objp->revision))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_validate_req (XDR *xdrs, validate_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->name_len))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->passwd_len))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->name, XDR_USER_NAME_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->passwd_md5, XDR_PASSWD_MD5_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_version_info (xdrs, &objp->ver))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_validate_resp_data (XDR *xdrs, validate_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->uid))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->name, XDR_USER_NAME_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->connect_id, XDR_CONNECT_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->pwd, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_validate_resp (XDR *xdrs, validate_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_validate_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_append_conn_req (XDR *xdrs, append_conn_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->type))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_append_conn_resp_data (XDR *xdrs, append_conn_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->connect_id, XDR_CONNECT_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_append_conn_resp (XDR *xdrs, append_conn_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_append_conn_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_logged_in_user (XDR *xdrs, logged_in_user *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->name, XDR_USER_NAME_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->ip, XDR_IPV4_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->port))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_pwd_req (XDR *xdrs, pwd_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_pwd_resp_data (XDR *xdrs, pwd_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->pwd, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_pwd_resp (XDR *xdrs, pwd_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_pwd_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_ll_req (XDR *xdrs, ll_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->path, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->to_peer))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_logged_in_user (xdrs, &objp->user))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_file_entry (XDR *xdrs, file_entry *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->name, XDR_FILE_NAME_MAX_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->type))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->c_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->a_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->m_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->mode))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		} else {
			IXDR_PUT_U_LONG(buf, objp->type);
			IXDR_PUT_U_LONG(buf, objp->size);
			IXDR_PUT_U_LONG(buf, objp->c_time);
			IXDR_PUT_U_LONG(buf, objp->a_time);
			IXDR_PUT_U_LONG(buf, objp->m_time);
			IXDR_PUT_U_LONG(buf, objp->mode);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->name, XDR_FILE_NAME_MAX_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->type))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->c_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->a_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->m_time))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->mode))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		} else {
			objp->type = IXDR_GET_U_LONG(buf);
			objp->size = IXDR_GET_U_LONG(buf);
			objp->c_time = IXDR_GET_U_LONG(buf);
			objp->a_time = IXDR_GET_U_LONG(buf);
			objp->m_time = IXDR_GET_U_LONG(buf);
			objp->mode = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->name, XDR_FILE_NAME_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->type))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->size))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->c_time))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->a_time))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->m_time))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->mode))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_ll_resp_data (XDR *xdrs, ll_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->total))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->this_nr))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->entries, XDR_FILE_ENTRY_MAX_CNT,
		sizeof (file_entry), (xdrproc_t) xdr_file_entry))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_ll_resp (XDR *xdrs, ll_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_ll_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_cd_req (XDR *xdrs, cd_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->path, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_cd_resp_data (XDR *xdrs, cd_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->pwd, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_cd_resp (XDR *xdrs, cd_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_cd_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_get_req (XDR *xdrs, get_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->path, XDR_DIR_PATH_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->to_peer))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_logged_in_user (xdrs, &objp->user))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_trans_entry (XDR *xdrs, trans_entry *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->this_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->mode))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}

		} else {
		IXDR_PUT_LONG(buf, objp->type);
		IXDR_PUT_LONG(buf, objp->this_size);
		IXDR_PUT_U_LONG(buf, objp->mode);
		IXDR_PUT_U_LONG(buf, objp->total_size);
		}
		 if (!xdr_vector (xdrs, (char *)objp->content, XDR_CONTENT_BLOCK_SIZE,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->this_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->mode))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}

		} else {
		objp->type = IXDR_GET_LONG(buf);
		objp->this_size = IXDR_GET_LONG(buf);
		objp->mode = IXDR_GET_U_LONG(buf);
		objp->total_size = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->content, XDR_CONTENT_BLOCK_SIZE,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->type))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->this_size))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->mode))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_u_int (xdrs, &objp->total_size))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->content, XDR_CONTENT_BLOCK_SIZE,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_get_resp_data (XDR *xdrs, get_resp_data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->total_files))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->file_idx))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_trans_entry (xdrs, &objp->entry))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_get_resp (XDR *xdrs, get_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_get_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->need_reply))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_put_req_data (XDR *xdrs, put_req_data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->total_files))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->file_idx))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_trans_entry (xdrs, &objp->entry))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_put_req (XDR *xdrs, put_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->to_peer))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_logged_in_user (xdrs, &objp->user))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_put_req_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->need_reply))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_put_resp (XDR *xdrs, put_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_common_resp (XDR *xdrs, common_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_write_msg_req (XDR *xdrs, write_msg_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->mtype))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->name, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->pid))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->length))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->mtext, XDR_NET_MSG_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_read_msg_req (XDR *xdrs, read_msg_req *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->mtype))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_read_msg_resp_data (XDR *xdrs, read_msg_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->mtype))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->name, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->pid))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->length))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->mtext, XDR_NET_MSG_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_read_msg_resp (XDR *xdrs, read_msg_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_read_msg_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_mp_stat_req (XDR *xdrs, mp_stat_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_mp_stat_resp_data (XDR *xdrs, mp_stat_resp_data *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->total_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->using_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->free_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		} else {
			IXDR_PUT_U_LONG(buf, objp->total_size);
			IXDR_PUT_LONG(buf, objp->total_nodes);
			IXDR_PUT_LONG(buf, objp->using_nodes);
			IXDR_PUT_LONG(buf, objp->free_nodes);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->total_size))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->total_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->using_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
			 if (!xdr_int (xdrs, &objp->free_nodes))
				 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
		} else {
			objp->total_size = IXDR_GET_U_LONG(buf);
			objp->total_nodes = IXDR_GET_LONG(buf);
			objp->using_nodes = IXDR_GET_LONG(buf);
			objp->free_nodes = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->total_size))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->total_nodes))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->using_nodes))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->free_nodes))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_mp_stat_resp (XDR *xdrs, mp_stat_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_mp_stat_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_directcmd_req (XDR *xdrs, directcmd_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->cmd, XDR_CMD_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_directcmd_resp_data (XDR *xdrs, directcmd_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->total_len))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->this_len))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->content, XDR_DIRECT_CMD_RESP_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_directcmd_resp (XDR *xdrs, directcmd_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_directcmd_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_who_req (XDR *xdrs, who_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->session_id, XDR_SESSION_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_who_resp_data (XDR *xdrs, who_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->total))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->this_nr))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->users, XDR_LOGGED_IN_USER_MAX_CNT,
		sizeof (logged_in_user), (xdrproc_t) xdr_logged_in_user))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_who_resp (XDR *xdrs, who_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_who_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_write_req (XDR *xdrs, write_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_logged_in_user (xdrs, &objp->user))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->len))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_WRITE_MSG_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_write_resp_data (XDR *xdrs, write_resp_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_WRITE_MSG_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}

bool_t
xdr_write_resp (XDR *xdrs, write_resp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_int (xdrs, &objp->flags))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_vector (xdrs, (char *)objp->message, XDR_RESP_MESSAGE_MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	 if (!xdr_write_resp_data (xdrs, &objp->data))
		 {printf("%s:%d\n", __func__, __LINE__); return FALSE;}
	return TRUE;
}
